In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('survey_results_public.csv', index_col = "Respondent")
schemea = pd.read_csv('survey_results_schema.csv', index_col = "Column")
# we can set index here as well as we are creating our data frame by passing in additional args like in schemea

In [3]:
df

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [4]:
df.columns

Index(['MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource', 'Employment',
       'Country', 'Student', 'EdLevel', 'UndergradMajor', 'EduOther',
       'OrgSize', 'DevType', 'YearsCode', 'Age1stCode', 'YearsCodePro',
       'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney', 'MgrWant', 'JobSeek',
       'LastHireDate', 'LastInt', 'FizzBuzz', 'JobFactors', 'ResumeUpdate',
       'CurrencySymbol', 'CurrencyDesc', 'CompTotal', 'CompFreq',
       'ConvertedComp', 'WorkWeekHrs', 'WorkPlan', 'WorkChallenge',
       'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev', 'CodeRevHrs', 'UnitTests',
       'PurchaseHow', 'PurchaseWhat', 'LanguageWorkedWith',
       'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [5]:
# to get multiple series(columns) 
df[["Hobbyist", "Student"]]

           Hobbyist         Student
Respondent
1               Yes              No
2                No  Yes, full-time
3               Yes              No
4                No              No
5               Yes              No
...             ...             ...
88377           Yes              No
88601            No             NaN
88802            No             NaN
88816            No             NaN
88863           Yes  Yes, full-time

[88883 rows x 2 columns]

In [6]:
# pd.set_option('display.max_columns',85)
# pd.set_option('display.max_rows', 85)

In [7]:
# pd.set_option('display.max_row', None)
# to show the maximum rolls

In [8]:
schemea["QuestionText"].sort_index()

Column
Age              What is your age (in years)? If you prefer not...
Age1stCode       At what age did you write your first line of c...
BetterLife       Do you think people born today will have a bet...
BlockchainIs     Blockchain / cryptocurrency technology is prim...
BlockchainOrg    How is your organization thinking about or imp...
                                       ...
WorkPlan                   How structured or planned is your work?
WorkRemote                         How often do you work remotely?
WorkWeekHrs       On average, how many hours per week do you work?
YearsCode        Including any education, how many years have y...
YearsCodePro     How many years have you coded professionally (...
Name: QuestionText, Length: 85, dtype: object

In [9]:
df.iloc[0]

MainBranch                 I am a student who is learning to code
Hobbyist                                                      Yes
OpenSourcer                                                 Never
OpenSource      The quality of OSS and closed source software ...
Employment                 Not employed, and not looking for work
                                      ...
Sexuality                                 Straight / Heterosexual
Ethnicity                                                     NaN
Dependents                                                     No
SurveyLength                                Appropriate in length
SurveyEase                             Neither easy nor difficult
Name: 1, Length: 84, dtype: object

In [10]:
# to get n numbers of column row use 2 brackets 
df.iloc[[0, 5]]
# meanwhile if i want to get the colums i input the index of the column i want

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
6,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,28.0,Man,No,Straight / Heterosexual,East Asian,No,Too long,Neither easy nor difficult

In [11]:
df.loc[[1,2]]

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [12]:
df.loc[1:4, ["Country", "OpenSource"]]
# the loc will use normal string to get the columns

,Country,OpenSource
Respondent,,
1,United Kingdom,The quality of OSS and closed source software ...
2,Bosnia and Herzegovina,The quality of OSS and closed source software ...
3,Thailand,The quality of OSS and closed source software ...
4,United States,The quality of OSS and closed source software ...

In [13]:
df["OpenSource"]

Respondent
1        The quality of OSS and closed source software ...
2        The quality of OSS and closed source software ...
3        The quality of OSS and closed source software ...
4        The quality of OSS and closed source software ...
5        OSS is, on average, of HIGHER quality than pro...
                               ...
88377    The quality of OSS and closed source software ...
88601    The quality of OSS and closed source software ...
88802                                                  NaN
88816    OSS is, on average, of HIGHER quality than pro...
88863    OSS is, on average, of HIGHER quality than pro...
Name: OpenSource, Length: 88883, dtype: object

In [14]:
# df.set_index("Respondent", inplace = True)
# use to set a coloumn as an index

In [15]:
# df.reset_index(inplace = True)
# used to reset the index back to default

In [16]:
schemea.loc["Sexuality", "QuestionText"]

'Which of the following do you currently identify as? Please select all that apply. If you prefer not to answer, you may leave this question blank.'

In [17]:
# pd.set_option('display.max_rows', None)

In [18]:
schemea.sort_index(ascending = False)
# if i want to make it in descending order, inside the brackets i can put ascending = false

                                                    QuestionText
Column
YearsCodePro   How many years have you coded professionally (...
YearsCode      Including any education, how many years have y...
WorkWeekHrs     On average, how many hours per week do you work?
WorkRemote                       How often do you work remotely?
WorkPlan                 How structured or planned is your work?
...                                                          ...
BlockchainOrg  How is your organization thinking about or imp...
BlockchainIs   Blockchain / cryptocurrency technology is prim...
BetterLife     Do you think people born today will have a bet...
Age1stCode     At what age did you write your first line of c...
Age            What is your age (in years)? If you prefer not...

[85 rows x 1 columns]

In [19]:
filt = (df["Hobbyist"] == "Yes") & (df["Student"] == "No")

In [20]:
# df[filt]
df.loc[filt, "Student"]
# df.loc[filt, "Country"]
# adding a ~ to the filter will negate the filter

Respondent
1        No
3        No
5        No
6        No
9        No
         ..
86566    No
86638    No
87352    No
88282    No
88377    No
Name: Student, Length: 52150, dtype: object

In [21]:
higher = (df["ConvertedComp"] > 8000)

In [22]:
# df.loc[higher, ["Country", "ConvertedComp"]] 
df.loc[higher, "ConvertedComp"]

Respondent
3          8820.0
4         61000.0
6        366420.0
9         95179.0
10        13293.0
           ...
88878    130000.0
88879     82488.0
88881     68745.0
88882    588012.0
88883     22915.0
Name: ConvertedComp, Length: 51372, dtype: float64

In [23]:
countries = ["Spain", "Germany","Czech Republic", "United States"]
cut = df["Country"].isin(countries)

In [24]:
df.loc[cut,"Country"]

Respondent
4         United States
13        United States
14              Germany
22        United States
23        United States
              ...
85642     United States
87739    Czech Republic
88212             Spain
88282     United States
88863             Spain
Name: Country, Length: 29183, dtype: object

In [25]:
git =  df["LanguageWorkedWith"].str.contains("Python", na =False)

In [26]:
df.loc[git, "LanguageWorkedWith"]

Respondent
1                          HTML/CSS;Java;JavaScript;Python
2                                      C++;HTML/CSS;Python
4                                      C;C++;C#;Python;SQL
5              C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
8        Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
                               ...
84539    Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
85738      Bash/Shell/PowerShell;C++;Python;Ruby;Other(s):
86566      Bash/Shell/PowerShell;HTML/CSS;Python;Other(s):
87739             C;C++;HTML/CSS;JavaScript;PHP;Python;SQL
88212                           HTML/CSS;JavaScript;Python
Name: LanguageWorkedWith, Length: 36443, dtype: object

In [27]:
df.columns = [x.upper() for x in df.columns]

In [28]:
df.rename(columns = {"MAINBRANCH" : "MAIN"}, inplace = True)

In [29]:
df.columns

Index(['MAIN', 'HOBBYIST', 'OPENSOURCER', 'OPENSOURCE', 'EMPLOYMENT',
       'COUNTRY', 'STUDENT', 'EDLEVEL', 'UNDERGRADMAJOR', 'EDUOTHER',
       'ORGSIZE', 'DEVTYPE', 'YEARSCODE', 'AGE1STCODE', 'YEARSCODEPRO',
       'CAREERSAT', 'JOBSAT', 'MGRIDIOT', 'MGRMONEY', 'MGRWANT', 'JOBSEEK',
       'LASTHIREDATE', 'LASTINT', 'FIZZBUZZ', 'JOBFACTORS', 'RESUMEUPDATE',
       'CURRENCYSYMBOL', 'CURRENCYDESC', 'COMPTOTAL', 'COMPFREQ',
       'CONVERTEDCOMP', 'WORKWEEKHRS', 'WORKPLAN', 'WORKCHALLENGE',
       'WORKREMOTE', 'WORKLOC', 'IMPSYN', 'CODEREV', 'CODEREVHRS', 'UNITTESTS',
       'PURCHASEHOW', 'PURCHASEWHAT', 'LANGUAGEWORKEDWITH',
       'LANGUAGEDESIRENEXTYEAR', 'DATABASEWORKEDWITH',
       'DATABASEDESIRENEXTYEAR', 'PLATFORMWORKEDWITH',
       'PLATFORMDESIRENEXTYEAR', 'WEBFRAMEWORKEDWITH',
       'WEBFRAMEDESIRENEXTYEAR', 'MISCTECHWORKEDWITH',
       'MISCTECHDESIRENEXTYEAR', 'DEVENVIRON', 'OPSYS', 'CONTAINERS',
       'BLOCKCHAINORG', 'BLOCKCHAINIS', 'BETTERLIFE', 'ITPERSON', 'OFFON',
       'SOCIALMEDIA', 'EXTRAVERSION', 'SCREENNAME', 'SOVISIT1ST',
       'SOVISITFREQ', 'SOVISITTO', 'SOFINDANSWER', 'SOTIMESAVED',
       'SOHOWMUCHTIME', 'SOACCOUNT', 'SOPARTFREQ', 'SOJOBS', 'ENTTEAMS',
       'SOCOMM', 'WELCOMECHANGE', 'SONEWCONTENT', 'AGE', 'GENDER', 'TRANS',
       'SEXUALITY', 'ETHNICITY', 'DEPENDENTS', 'SURVEYLENGTH', 'SURVEYEASE'],
      dtype='object')

In [30]:
# pd.set_option("display.max_row", 85)

In [31]:
schemea

                                                   QuestionText
Column
Respondent    Randomized respondent ID number (not in order ...
MainBranch    Which of the following options best describes ...
Hobbyist                                Do you code as a hobby?
OpenSourcer         How often do you contribute to open source?
OpenSource    How do you feel about the quality of open sour...
...                                                         ...
Sexuality     Which of the following do you currently identi...
Ethnicity     Which of the following do you identify as? Ple...
Dependents    Do you have any dependents (e.g., children, el...
SurveyLength  How do you feel about the length of the survey...
SurveyEase    How easy or difficult was this survey to compl...

[85 rows x 1 columns]

In [32]:
df.apply(pd.Series.min)
# this will give me an errror buh jst keep it

TypeError: '<=' not supported between instances of 'str' and 'float'

In [ ]:
# df.applymap(len)
# wouldn't work because of the data type i.e float and strings

In [ ]:
df["HOBBYIST"] = df['HOBBYIST'].map({"Yes" : "True", "No" : "False"})
changwes

In [ ]:
df["HOBBYIST"]

In [ ]:
df["HOBBYIST"]+ " " + df["STUDENT"]

In [ ]:
df["okay"] = df["HOBBYIST"] + " " +df["STUDENT"]

In [ ]:
df

In [ ]:
# i can split this okay by
# df["okay"].str.split(" ", expand = True)
# the .str turns it to string
# the .split turn splits the string where ever it sees space
# and the expand =  True expands the the strings adding them into different columns

# next i apply
# df[["the_first_column_name", "the_second_column_namw"]] = df["okay"].str.split(" ", expand = True)

In [ ]:
df.drop(columns = ["okay"], inplace = True)

In [ ]:
new_df = pd.DataFrame({"HOBBYIST": ["True"]})
df = new_df.append(df, ignore_index=True)

In [ ]:
df